2bTransitionsevent/2bTransitionsevent/Areas/Admin/Controllers/ExchangeAdminController.cs
using _2bTransitionsevent.ActionFilters;
using _2bTransitionsevent.Areas.Admin.ViewModels.Exchange;
using _2bTransitionsevent.Models;
using _2bTransitionsevent.Models.Cmind;
using _2bTransitionsevent.Repositories;
using _2bTransitionsevent.Utility.Cmind;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2bTransitionsevent.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class ExchangeAdminController : BaseAdminController
    {
        private ExchangeRepository exchangeRepository = new ExchangeRepository();
        // GET: Admin/ExchangeAdmin
        public ActionResult Index(ExchangeIndexView model)
        {
            var query = exchangeRepository.Query(model.StoreName, model.StoreID, model.SerialNumber/*, null ,null*/);
            var pageResult = query.ToPageResult<Exchange>(model);
            model.PageResult = Mapper.Map<PageResult<ExchangeView>>(pageResult);
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            ExchangeView model;
            if (id == 0)
            {
                model = new ExchangeView();
            }
            else
            {
                var query = exchangeRepository.GetById(id);
                model = Mapper.Map<ExchangeView>(query);
            }
            return View(model);
        }

        public ActionResult Statistical(ExchangeIndexView model)
        {

            //model.StartDate = DateTime.Parse("2021/09/01");
            //model.EndDate = DateTime.Parse("2021/09/15");
            var query = exchangeRepository.Query(model.StoreName, model.StoreID, null).AsQueryable().GroupBy(x => x.StoreID).Select(x => x.FirstOrDefault());
            //var query = exchangeRepository.Query(model.StoreName, model.StoreID, null, model.StartDate, model.EndDate).AsQueryable().GroupBy(x => x.StoreID).Select(x => x.FirstOrDefault());
            var pageResult = query.ToPageResult2<Exchange>(model);
            model.PageResult = Mapper.Map<PageResult<ExchangeView>>(pageResult);
            model.PageResult.Data = model.PageResult.Data.OrderByDescending(p => p.TotalCount);
            return View(model);
        }
    }
}

2bTransitionsevent/2bTransitionsevent/Areas/Admin/Views/ExchangeAdmin/Edit.cshtml
@model _2bTransitionsevent.Areas.Admin.ViewModels.Exchange.ExchangeView
@{
    ViewBag.Title = "序號兌換管理";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>序號兌換管理</h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-primary">

                @using (Html.BeginForm("Edit", "ExchangeAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.ID)

                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.StoreID)
                                @Html.TextBoxFor(model => model.StoreID, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.StoreName)
                                @Html.TextBoxFor(model => model.StoreName, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Address)
                                @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Sales)
                                @Html.TextBoxFor(model => model.Sales, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Phone)
                                @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.SerialNumber)
                                @Html.TextBoxFor(model => model.SerialNumber, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Code)
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="card-footer">
                        @Html.ActionLink("回列表", "Index", null, new { @class = "btn btn-default" })
                    </div>
                    }
                </div>
        </div>
    </div>
</section>

2bTransitionsevent/2bTransitionsevent/Areas/Admin/Views/ExchangeAdmin/Index.cshtml
@model  _2bTransitionsevent.Areas.Admin.ViewModels.Exchange.ExchangeIndexView
@{
    ViewBag.Title = "Index";
    var title = "序號兌換";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>序號兌換管理</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "ExchangeAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
            <div class="card-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.StoreID, new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-12">
                        @Html.TextBoxFor(model => model.StoreID, new { @class = "form-control", @placeholder = "商店統編" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.StoreName, new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-12">
                        @Html.TextBoxFor(model => model.StoreName, new { @class = "form-control", @placeholder = "商店名稱" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SerialNumber, new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-12">
                        @Html.TextBoxFor(model => model.SerialNumber, new { @class = "form-control", @placeholder = "序號" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-info">搜尋</button>
                    </div>
                </div>
            </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">@title 列表</h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row  table-responsive">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th data-sorting="StoreID">
                                                @Html.DisplayNameFor(model => model.StoreID)
                                            </th>
                                            <th data-sorting="StoreName">
                                                @Html.DisplayNameFor(model => model.StoreName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Sales)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.SerialNumber)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Code)
                                            </th>
                                            <th data-sorting="CreateTime">
                                                @Html.DisplayNameFor(model => model.CreateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th data-sorting="StoreID">
                                                @Html.DisplayNameFor(model => model.StoreID)
                                            </th>
                                            <th data-sorting="StoreName">
                                                @Html.DisplayNameFor(model => model.StoreName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Sales)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.SerialNumber)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Code)
                                            </th>
                                            <th data-sorting="CreateTime">
                                                @Html.DisplayNameFor(model => model.CreateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                        <tr>
                                            <td>
                                                @item.StoreID
                                            </td>
                                            <td>
                                                @item.StoreName
                                            </td>
                                            <td>
                                                @item.Sales
                                            </td>
                                            <td>
                                                @item.SerialNumber
                                            </td>
                                            <td>
                                                @item.Code
                                            </td>
                                            <td>
                                                @item.CreateTime.ToString("yyyy/MM/dd HH:mm")
                                            </td>
                                            <td>
                                                @Html.ActionLink("查看", "Edit", "ExchangeAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}

2bTransitionsevent/2bTransitionsevent/Areas/Admin/Views/ExchangeAdmin/Statistical.cshtml
@model  _2bTransitionsevent.Areas.Admin.ViewModels.Exchange.ExchangeIndexView
@{
    ViewBag.Title = "Statistical";
    var title = "商店兌換統計表";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>商店兌換統計表</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Statistical", "ExchangeAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.StoreID, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.StoreID, new { @class = "form-control", @placeholder = "商店統編" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.StoreName, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.StoreName, new { @class = "form-control", @placeholder = "商店名稱" })
                            </div>
                        </div>
                        @*<div class="form-group">
                            @Html.LabelFor(model => model.StartDate, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control", @placeholder = "商店名稱" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.EndDate, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control", @placeholder = "商店名稱" })
                            </div>
                        </div>*@
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">@title </h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_length" id="">
                                    <label>
                                        共 @Model.PageResult.Data.Count() 筆
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-6">
                            </div>
                        </div>
                        <div class="row  table-responsive">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.StoreID)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.StoreName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.TotalCount)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.StoreID)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.StoreName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.TotalCount)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            <tr>
                                                <td>
                                                    @item.StoreID
                                                </td>
                                                <td>
                                                    @item.StoreName
                                                </td>
                                                <td>
                                                    @item.TotalCount
                                                </td>
                                                <td>
                                                    @Html.ActionLink("本商店序號兌換列表", "Index", "ExchangeAdmin", new { StoreID = item.StoreID }, new { @class = "btn btn-primary" })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @*@Html.Partial("_PageAdmin", Model.PageResult)*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
    @*<link rel="stylesheet" href="//apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(function () {
            $("#StartDate").datepicker({
                dateFormat: "yy/mm/dd"
            });
            $("#EndDate").datepicker({
                dateFormat: "yy/mm/dd"
            });
        });
    </script>*@
}